export enum ProjectRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  FIELD_ENGINEER = 'FIELD_ENGINEER',
  SUPERINTENDENT = 'SUPERINTENDENT',
  SUBCONTRACTOR = 'SUBCONTRACTOR',
  VIEWER = 'VIEWER',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  PRE_CONSTRUCTION = 'PRE_CONSTRUCTION',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
}

export enum RfiStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  RESPONDED = 'RESPONDED',
  CLOSED = 'CLOSED',
  OVERDUE = 'OVERDUE',
}

export enum SubmittalStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  APPROVED_AS_NOTED = 'APPROVED_AS_NOTED',
  REVISE_AND_RESUBMIT = 'REVISE_AND_RESUBMIT',
  REJECTED = 'REJECTED',
}

export enum DrawingDiscipline {
  ARCHITECTURAL = 'ARCHITECTURAL',
  STRUCTURAL = 'STRUCTURAL',
  MECHANICAL = 'MECHANICAL',
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  CIVIL = 'CIVIL',
  LANDSCAPE = 'LANDSCAPE',
  FIRE_PROTECTION = 'FIRE_PROTECTION',
  OTHER = 'OTHER',
}

export enum ChangeOrderStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  VOID = 'VOID',
}

export enum ContractType {
  PRIME = 'PRIME',
  SUBCONTRACT = 'SUBCONTRACT',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
}

export enum WeatherCondition {
  CLEAR = 'CLEAR',
  PARTLY_CLOUDY = 'PARTLY_CLOUDY',
  CLOUDY = 'CLOUDY',
  RAIN = 'RAIN',
  SNOW = 'SNOW',
  WIND = 'WIND',
  STORM = 'STORM',
  FOG = 'FOG',
}
